In [1]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))

True
1
NVIDIA GeForce RTX 2060


In [2]:
# Basics
x = torch.randn(3, requires_grad=True)
print(x)

y = x + 2
print(y)

z = y * y * 2
# z = z.mean()
print(z)

v = torch.tensor([0.1, 1.0, .001], dtype=torch.float32)

z.backward(v) # dz/dx
print(x.grad)

tensor([-0.9178, -1.7889,  0.0736], requires_grad=True)
tensor([1.0822, 0.2111, 2.0736], grad_fn=<AddBackward0>)
tensor([2.3425, 0.0891, 8.5994], grad_fn=<MulBackward0>)
tensor([0.4329, 0.8444, 0.0083])


In [4]:
# Gradient
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights * 3).sum()

    model_output.backward()

    print(weights.grad)

    weights.grad.zero_()

# optimizer = torch.optim.SGD(weights, lr=0.01)
# optimizer.step()
# optimizer.zero_grad()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [5]:
# Backpropagation with gradient
x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad=True)

# forward pass to compute the loss
y_hat = w * x
loss = (y_hat -y) ** 2
print(loss)

# backward pass
loss.backward()
print(w.grad)

### updatae weights
### next forward computation and backward propagation

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)
